def ss58_decode(address: str, valid_ss58_format: int | None = None) -> str: ...
def ss58_encode(address: str | bytes, ss58_format: int = 42) -> str: ...
def is_valid_ss58_address(value: str, valid_ss58_format: int | None = None) -> bool: ...
def get_ss58_format(ss58_address: str) -> int: ...
