name: check-python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  python-checks:
    concurrency:
      group: python-checks-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Check code with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'check'
          src: './keyless-python'

      - name: Check code formatting with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          src: './keyless-python'

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: cd keyless-python && mypy .

      - name: Run tests
        run: |
            cd keyless-python
            pip install -r requirements.txt
            python3 -m unittest tests.test_encoding tests.test_ss58 tests.test_names
